// Heller — translation dictionary with v4 content mutations applied statically.
// v4 mutations (from content v4.js) are applied inline — no runtime mutation needed.

function firstSentence(s: string) {
  return (s || '').split(/[.!?]/)[0] + '.';
}

const DICT_BASE = {
  de: {
    topStrip: {
      l: "HELLER · STUDIO FÜR PREMIUM-WEBAUFTRITTE",
      m: "Berlin · Anno MMXXVI",
    },
    nav: {
      leistungen: "Leistungen",
      ablauf: "Ablauf",
      beispiele: "Beispiele",
      preise: "Preise",
      faq: "FAQ",
      login: "Anmelden",
      cta: "Erstgespräch",
    },
    hero: {
      mark: "Heller — Positionierung",
      title: "Moderne Websites,\ndie [[Vertrauen]] schaffen\nund neue Anfragen [[gewinnen.]]",
      lead: "Premium-Webauftritte für Handwerk, Praxen und Studios in Deutschland. Strategie, Design, Build — aus einer Hand.",
      primary: "Kostenloses Erstgespräch sichern",
      secondary: "Beispiele ansehen",
      stat1v: "200+ Stunden", stat1l: "Designarbeit pro Projekt",
      stat2v: "4–6 Wochen",  stat2l: "Konzept bis Launch",
      stat3v: "DSGVO",       stat3l: "von Anfang an",
      mockBadge: "Websites für lokale Dienstleister",
      mockTitle: "[[Handwerk]] aus Berlin —\nseit drei Generationen.",
      mockSub: "Maßgefertigte Möbel und Innenausbau. Persönliche Beratung in unserer Werkstatt in Kreuzberg.",
      mockBtn: "Termin anfragen →",
      mockTile1: "Maßmöbel", mockTile2: "Innenausbau", mockTile3: "Reparaturen",
      phoneTitle: "Handwerk aus Berlin.",
      phoneSub: "Möbel, Ausbau, Reparatur — persönlich beraten.",
      phoneBtn: "Termin →",
      proofMobileL: "Mobile-Score",
      proofMobileV: "100 / 100",
      proofRevV: "4,9", proofRevSub: "47 Bewertungen",
    },
    marquee: [
      "Premium-Webauftritte",
      "[[für lokale Dienstleister]]",
      "Made in Germany",
      "DSGVO-konform",
      "[[4–6 Wochen bis Launch]]",
      "Strategie · Design · Umsetzung",
      "Mobile-first",
      "[[aus einer Hand]]",
    ],
    trust: [
      "Für lokale Dienstleister in Deutschland",
      "Strategie, Design und Umsetzung aus einer Hand",
      "Mobile-first umgesetzt",
      "Klare Prozesse",
      "Laufende Betreuung optional",
    ],
    problem: {
      mark: "Das Problem",
      title: "Ihre Website wirkt [[älter,]] als Ihr Unternehmen wirklich ist.",
      lead: "Ihr Unternehmen ist seriös — Ihre Website sollte es auch zeigen.",
      pains: [
        "Veraltetes Design vermittelt einen falschen Eindruck",
        "Auf dem Smartphone kaum benutzbar",
        "Vertrauenssignale fehlen",
        "Unklare Struktur, schwache Anfragen",
      ],
      oldLogo: "Tischlerei Müller",
      oldH: "Willkommen!!!",
      oldSub: "Wir machen Möbel und Reparaturen seit 1962. Rufen Sie uns an unter 030 / 12 34 56 78 oder besuchen Sie uns in der Werkstatt!",
      oldBtn: "► Hier klicken",
    },
    ba: {
      mark: "Vorher / Nachher",
      title: "Ein moderner Auftritt macht den [[Unterschied.]]",
      lead: "Ziehen Sie den Regler — derselbe Betrieb, derselbe Inhalt, ein anderer erster Eindruck.",
      before: "Vorher", after: "Nachher",
    },
    audience: {
      mark: "Für wen wir arbeiten",
      title: "Für lokale Dienstleister, die online [[professioneller]] wirken möchten.",
      tiles: [
        { name: "Handwerksbetriebe", sub: "Tischlereien, Schreinereien, Maler, Elektriker — Qualität, die sich auf der Website widerspiegelt." },
        { name: "Arzt- und Therapiepraxen", sub: "Ruhig, vertrauensvoll, klar strukturiert." },
        { name: "Studios", sub: "Yoga, Pilates, Fitness — Atmosphäre digital übertragen." },
        { name: "Coaches & Berater", sub: "Persönliche Marke, professionell präsentiert." },
        { name: "Weitere lokale Dienstleister", sub: "Kanzleien, Gastronomie, Beauty — wir hören zu." },
      ],
      branche: "Branche",
    },
    benefits: {
      mark: "Leistungen",
      title: "Mehr als nur eine [[schöne]] Website.",
      lead: "Sechs Standards — kein Aufpreis.",
      cards: [
        { t: "Mehr Vertrauen",        d: "Ein professioneller Auftritt schafft Vertrauen ab dem ersten Besuch." },
        { t: "Mehr Anfragen",         d: "Klare Struktur und starke CTAs führen Besucher gezielt zur Kontaktaufnahme." },
        { t: "Premium-Wahrnehmung",   d: "Ihre Website spiegelt die Qualität Ihrer Arbeit wider und positioniert Sie hochwertig." },
        { t: "Auf allen Geräten",     d: "Saubere Darstellung auf Smartphone, Tablet und Desktop — Mobile-first entwickelt." },
        { t: "Klare Nutzerführung",   d: "Besucher verstehen schneller, wer Sie sind und warum Sie die richtige Wahl sind." },
        { t: "Rechtlich vorbereitet", d: "Impressum, Datenschutz und Pflichtseiten werden von Anfang an mitgedacht." },
      ],
    },
    showcase: {
      mark: "Beispiel-Konzept",
      title: "Vom veralteten Handwerksbetrieb zum [[modernen]] Premium-Auftritt.",
      lead: "Vier Stationen. Eine Transformation.",
      stops: [
        {
          label: "Status quo",
          title: "Eine Website aus [[2008.]]",
          body: "Veraltetes Design, unklare Struktur, schwache mobile Darstellung.",
          points: [
            "Hierarchie fehlt — alles wirkt gleich wichtig",
            "Schriftbild aus den Office-Vorlagen",
          ],
        },
        {
          label: "Strategie",
          title: "Struktur und [[Hierarchie.]]",
          body: "Wir kartieren Inhalte neu, gewichten Aussagen, schärfen die Nutzerführung.",
          points: [
            "Eine Botschaft, ein Satz, eine Handlung",
            "Leistungen als klar lesbare Module",
          ],
        },
        {
          label: "Design",
          title: "Typografie, Farbe, [[Raum.]]",
          body: "Die Designrichtung übernimmt das Sprechen, bevor das erste Wort gelesen wird.",
          points: [
            "Schriftpaarung mit redaktioneller Tiefe",
            "Reduzierte, warmweiße Farbpalette",
          ],
        },
        {
          label: "Resultat",
          title: "Derselbe Betrieb, ein [[anderer]] Eindruck.",
          body: "Modern, mobil-optimiert, technisch sauber, rechtlich vorbereitet.",
          points: [
            "Mobile-Score 100 / 100",
            "Klare Kontaktwege und Termin-CTA",
          ],
        },
      ],
    },
    process: {
      mark: "Ablauf",
      title: "In [[vier Schritten]] zu Ihrer neuen Premium-Website.",
      lead: "Klar strukturiert, ohne Überraschungen. Sie wissen jederzeit, wo wir stehen und was als Nächstes kommt.",
      steps: [
        { t: "Kostenloses Erstgespräch",   d: "Wir analysieren Ihre aktuelle Website, Ihre Ziele und prüfen, wie wir helfen können." },
        { t: "Konzept und Designrichtung", d: "Wir entwickeln Struktur, Designrichtung und Seitenaufbau passend zu Ihrer Branche und Marke." },
        { t: "Umsetzung und Launch",       d: "Wir setzen die Website technisch um, optimieren sie für alle Geräte und begleiten den Launch." },
        { t: "Betreuung optional",         d: "Auf Wunsch übernehmen wir Updates, Änderungen, neue Inhalte und laufende Optimierung." },
      ],
    },
    ai: {
      mark: "Produktion",
      title: "Ein moderner Produktionsprozess — ohne Abstriche bei [[Qualität.]]",
      lead: "Wir kombinieren strategische Konzeption mit einem KI-gestützten Produktionsprozess und einem spezialisierten Design-Team. So entstehen hochwertige Websites mit klaren Abläufen, schneller Umsetzung und konsistenter Qualität.",
      features: [
        { t: "Strategische Konzeption", d: "Jedes Projekt beginnt mit Verständnis Ihrer Branche, Zielgruppe und Positionierung." },
        { t: "KI-gestützte Produktion", d: "Wiederkehrende Aufgaben automatisiert, kreative Entscheidungen menschlich getroffen." },
        { t: "4–6 Wochen bis Launch",   d: "Klar getaktet, transparent kommuniziert — Sie wissen jederzeit, wo wir stehen." },
      ],
      cardTitle: "Produktion · Tischlerei Müller",
      cardSub: "Projekt #2406 — Konzeptphase",
      status: "Aktiv",
      tasks: [
        { label: "Briefing-Analyse",         time: "0:42" },
        { label: "Wettbewerbs-Recherche",    time: "1:18" },
        { label: "Designrichtung erstellen", time: "2:04" },
        { label: "Struktur und Wireframes",  time: "3:21" },
        { label: "Mobile Layout prüfen",     time: "läuft" },
      ],
    },
    portfolio: {
      mark: "Referenzen",
      title: "Moderne Webauftritte für [[unterschiedliche]] Branchen.",
      lead: "Sechs Beispielkonzepte — jeweils auf die Branche, die Zielgruppe und die Werte des Betriebs zugeschnitten.",
      cards: [
        { name: "Tischlerei Müller", tag: "Handwerk · Berlin" },
        { name: "Praxis Dr. Sommer", tag: "Arztpraxis · München" },
        { name: "Studio Lichtraum",  tag: "Yoga · Hamburg" },
        { name: "Kanzlei Weiss",     tag: "Recht · Frankfurt" },
        { name: "Café Salbei",       tag: "Gastronomie · Köln" },
        { name: "Friseur Kontur",    tag: "Beauty · Stuttgart" },
      ],
    },
    pricing: {
      mark: "Preise",
      title: "[[Klare]] Projektpreise für einen professionellen Webauftritt.",
      lead: "Transparente Preisrahmen — der endgültige Preis hängt vom Umfang ab und wird im Erstgespräch klar definiert.",
      cards: [
        {
          tag: "Einstieg", name: "Unterseiten",
          price: "500–2.000", unit: "pro Unterseite",
          features: ["Eigenständiges Layout", "Textstruktur und SEO-Grundlage", "Mobile-optimiert", "Integration in bestehende Website"],
          cta: "Projekt besprechen",
        },
        {
          tag: "Komplettpaket", pop: "Beliebt", name: "Website-Projekt",
          price: "3.000–5.000", unit: "je nach Umfang und Konzeptionsaufwand",
          features: ["Konzept, Design und Entwicklung", "Bis zu 8 Hauptseiten", "Mobile-first umgesetzt", "SEO-Grundausstattung", "Impressum, Datenschutz vorbereitet", "Launch-Begleitung"],
          cta: "Erstgespräch sichern",
        },
        {
          tag: "Optional", name: "Laufende Betreuung",
          price: "300–800", unit: "€ / Monat · monatlich kündbar",
          features: ["Kleinere Änderungen und Updates", "Neue Bilder und Texte einpflegen", "Technische Wartung und Sicherheit", "Laufende Optimierung"],
          cta: "Mehr erfahren",
        },
      ],
      footnote: "Alle Preise zzgl. MwSt. · Der endgültige Preis wird nach dem Erstgespräch verbindlich angeboten.",
    },
    faq: {
      mark: "Häufige Fragen",
      title: "Antworten auf die Fragen, die wir am [[häufigsten]] hören.",
      items: [
        { q: "Wie lange dauert ein Projekt?",            a: "Vier bis sechs Wochen vom Erstgespräch bis zum Launch." },
        { q: "Muss ich Texte und Bilder selbst liefern?", a: "Sie liefern die Inhalte — wir strukturieren, kürzen und schärfen sie." },
        { q: "Wird die Website mobil optimiert?",         a: "Ja, ausnahmslos." },
        { q: "Gibt es laufende Betreuung?",               a: "Optional." },
        { q: "Können später Änderungen gemacht werden?",  a: "Selbstverständlich." },
      ],
    },
    cta: {
      mark: "Bereit zu starten",
      title: "Bereit für eine Website, die zur [[Qualität]] Ihrer Arbeit passt?",
      body: "Wenn Ihre aktuelle Website nicht mehr zeigt, wie professionell Ihr Unternehmen wirklich ist, lassen Sie uns gemeinsam prüfen, wie ein moderner Premium-Auftritt für Sie aussehen könnte.",
      primary: "Kostenloses Erstgespräch sichern",
      secondary: "Beispiele ansehen",
      micro: "Antwort innerhalb von 24 h · keine Beratungsgebühr · auf Deutsch oder Englisch",
    },
    footer: {
      tag: "Premium-Websites für lokale Dienstleister in Deutschland. Strategie, Design und Umsetzung aus einer Hand.",
      colA: "Leistungen", colALinks: [["Website-Projekt", "#leistungen"], ["Unterseiten", "#leistungen"], ["Laufende Betreuung", "#leistungen"], ["Ablauf", "#ablauf"]],
      colB: "Unternehmen", colBLinks: [["Über Heller", "#"], ["Referenzen", "#referenzen"], ["FAQ", "#faq"], ["Kontakt", "#kontakt"]],
      colC: "Kontakt", colCLinks: [["hallo@heller.de", "mailto:hallo@heller.de"], ["+49 30 000 000", "tel:+4930000000"], ["LinkedIn", "#"]],
      copyright: "© 2026 Heller. Alle Rechte vorbehalten.",
      legal: [["Impressum", "#"], ["Datenschutz", "#"], ["AGB", "#"]],
    },
  },

  en: {
    topStrip: {
      l: "HELLER · STUDIO FOR PREMIUM WEB PRESENCES",
      m: "Berlin · Anno MMXXVI",
    },
    nav: {
      leistungen: "Services",
      ablauf: "Process",
      beispiele: "Examples",
      preise: "Pricing",
      faq: "FAQ",
      login: "Sign in",
      cta: "Consultation",
    },
    hero: {
      mark: "Heller — Positioning",
      title: "Modern websites\nthat build [[trust]]\nand win new [[inquiries.]]",
      lead: "Premium websites for tradesmen, practices and studios in Germany. Strategy, design, build — from one team.",
      primary: "Book a free initial consultation",
      secondary: "View examples",
      stat1v: "200+ hours", stat1l: "of design per project",
      stat2v: "4–6 weeks",  stat2l: "concept to launch",
      stat3v: "GDPR",       stat3l: "ready from day one",
      mockBadge: "Websites for local service businesses",
      mockTitle: "[[Craftsmanship]] from Berlin —\nthree generations strong.",
      mockSub: "Custom furniture and interior fit-out. Personal consultation in our Kreuzberg workshop.",
      mockBtn: "Request an appointment →",
      mockTile1: "Custom furniture", mockTile2: "Fit-out", mockTile3: "Repairs",
      phoneTitle: "Craftsmanship from Berlin.",
      phoneSub: "Furniture, fit-out, repairs — advised in person.",
      phoneBtn: "Book →",
      proofMobileL: "Mobile score",
      proofMobileV: "100 / 100",
      proofRevV: "4.9", proofRevSub: "47 reviews",
    },
    marquee: [
      "Premium web presences",
      "[[for local service businesses]]",
      "Made in Germany",
      "GDPR-compliant",
      "[[4–6 weeks to launch]]",
      "Strategy · Design · Build",
      "Mobile-first",
      "[[from a single team]]",
    ],
    trust: [
      "For local service businesses across Germany",
      "Strategy, design and build from a single team",
      "Mobile-first throughout",
      "Clear, structured process",
      "Ongoing care optional",
    ],
    problem: {
      mark: "The problem",
      title: "Your website looks [[older]] than your business actually is.",
      lead: "Your business is serious — your website should show it.",
      pains: [
        "Dated design gives the wrong impression",
        "Barely usable on a phone",
        "Trust signals missing",
        "Unclear structure, weak inquiries",
      ],
      oldLogo: "Tischlerei Müller",
      oldH: "Welcome!!!",
      oldSub: "We make furniture and repairs since 1962. Call us at 030 / 12 34 56 78 or visit us at the workshop!",
      oldBtn: "► Click here",
    },
    ba: {
      mark: "Before / After",
      title: "A modern presence makes the [[difference.]]",
      lead: "Drag the slider — same business, same content, a different first impression.",
      before: "Before", after: "After",
    },
    audience: {
      mark: "Who we work with",
      title: "For local service businesses that want to feel [[more professional]] online.",
      tiles: [
        { name: "Tradesmen",          sub: "Joiners, carpenters, painters, electricians — quality that shows on the website." },
        { name: "Medical practices",  sub: "Calm, trustworthy, clearly structured." },
        { name: "Studios",            sub: "Yoga, Pilates, fitness — atmosphere translated to the screen." },
        { name: "Coaches & advisors", sub: "Personal brand, professionally presented." },
        { name: "Other local services", sub: "Law firms, hospitality, beauty — we listen first." },
      ],
      branche: "Sector",
    },
    benefits: {
      mark: "Services",
      title: "More than just a [[beautiful]] website.",
      lead: "Six standards — no upcharge.",
      cards: [
        { t: "More trust",        d: "A professional presence builds trust from the first visit." },
        { t: "More inquiries",    d: "Clear structure and strong CTAs guide visitors deliberately toward getting in touch." },
        { t: "Premium perception", d: "Your website reflects the quality of your work and positions you at the top of your market." },
        { t: "On every device",   d: "Clean presentation across phone, tablet and desktop — built mobile-first." },
        { t: "Clear navigation",  d: "Visitors understand faster who you are and why you're the right choice." },
        { t: "Legally prepared",  d: "Imprint, privacy and required pages are accounted for from the start." },
      ],
    },
    showcase: {
      mark: "Example concept",
      title: "From outdated workshop site to [[modern]] premium presence.",
      lead: "Four stops. One transformation.",
      stops: [
        {
          label: "Status quo",
          title: "A website from [[2008.]]",
          body: "Outdated design, unclear structure, poor mobile experience.",
          points: [
            "No hierarchy — everything looks equally important",
            "Office-template typography",
          ],
        },
        {
          label: "Strategy",
          title: "Structure and [[hierarchy.]]",
          body: "We re-map the content, weight the messages, sharpen the navigation.",
          points: [
            "One message, one sentence, one action",
            "Services as clearly readable modules",
          ],
        },
        {
          label: "Design",
          title: "Typography, colour, [[space.]]",
          body: "The design direction does the talking before the first word is read.",
          points: [
            "Type pairing with editorial depth",
            "Reduced, warm-white palette",
          ],
        },
        {
          label: "Result",
          title: "Same business, a [[different]] impression.",
          body: "Modern, mobile-optimized, technically sound, legally prepared.",
          points: [
            "Mobile score 100 / 100",
            "Clear contact paths and appointment CTA",
          ],
        },
      ],
    },
    process: {
      mark: "Process",
      title: "[[Four steps]] to your new premium website.",
      lead: "Clearly structured, no surprises. You always know where we are and what comes next.",
      steps: [
        { t: "Free initial consultation",  d: "We analyze your current website, your goals, and check how we can help." },
        { t: "Concept and design direction", d: "We develop structure, design direction and page layout to fit your sector and brand." },
        { t: "Build and launch",            d: "We implement the site, optimize it for every device, and accompany the launch." },
        { t: "Ongoing care, optional",      d: "On request, we handle updates, edits, new content and continuous optimization." },
      ],
    },
    ai: {
      mark: "Production",
      title: "A modern production process — without compromise on [[quality.]]",
      lead: "We combine strategic conception with an AI-supported production process and a specialized design team. The result: high-quality websites delivered on a clear schedule and at consistent quality.",
      features: [
        { t: "Strategic conception",   d: "Every project begins with understanding your sector, audience and positioning." },
        { t: "AI-supported production", d: "Repetitive work automated, creative decisions made by humans." },
        { t: "4–6 weeks to launch",     d: "Clearly scheduled, transparently communicated — you always know where we are." },
      ],
      cardTitle: "Production · Tischlerei Müller",
      cardSub: "Project #2406 — Concept phase",
      status: "Active",
      tasks: [
        { label: "Brief analysis",          time: "0:42" },
        { label: "Competitive research",    time: "1:18" },
        { label: "Design direction draft",  time: "2:04" },
        { label: "Structure and wireframes", time: "3:21" },
        { label: "Mobile layout check",     time: "running" },
      ],
    },
    portfolio: {
      mark: "References",
      title: "Modern web presences for [[different]] sectors.",
      lead: "Six concept examples — each tailored to the sector, audience and values of the business.",
      cards: [
        { name: "Tischlerei Müller", tag: "Trades · Berlin" },
        { name: "Praxis Dr. Sommer", tag: "Medical · Munich" },
        { name: "Studio Lichtraum",  tag: "Yoga · Hamburg" },
        { name: "Kanzlei Weiss",     tag: "Law · Frankfurt" },
        { name: "Café Salbei",       tag: "Hospitality · Cologne" },
        { name: "Friseur Kontur",    tag: "Beauty · Stuttgart" },
      ],
    },
    pricing: {
      mark: "Pricing",
      title: "[[Clear]] project pricing for a professional web presence.",
      lead: "Transparent price ranges — the final price depends on scope and is defined precisely in the initial consultation.",
      cards: [
        {
          tag: "Entry", name: "Sub-pages",
          price: "500–2,000", unit: "per sub-page",
          features: ["Standalone layout", "Text structure and SEO foundation", "Mobile-optimized", "Integration into your existing site"],
          cta: "Discuss a project",
        },
        {
          tag: "Complete package", pop: "Most chosen", name: "Website project",
          price: "3,000–5,000", unit: "depending on scope and conception effort",
          features: ["Concept, design and build", "Up to 8 main pages", "Mobile-first throughout", "SEO foundation in place", "Imprint and privacy prepared", "Launch support"],
          cta: "Book a consultation",
        },
        {
          tag: "Optional", name: "Ongoing care",
          price: "300–800", unit: "€ / month · cancellable monthly",
          features: ["Smaller edits and updates", "New images and texts added", "Technical maintenance and security", "Continuous optimization"],
          cta: "Learn more",
        },
      ],
      footnote: "All prices excl. VAT · The final price is binding after the initial consultation.",
    },
    faq: {
      mark: "Frequent questions",
      title: "Answers to the questions we hear [[most often.]]",
      items: [
        { q: "How long does a project take?",                a: "Four to six weeks from the first call to launch." },
        { q: "Do I have to supply texts and images?",        a: "You provide the content — we structure, trim and sharpen it." },
        { q: "Will the site be mobile-optimized?",           a: "Yes, without exception." },
        { q: "Is there ongoing care?",                       a: "Optional." },
        { q: "Can changes be made later?",                   a: "Of course." },
      ],
    },
    cta: {
      mark: "Ready to start",
      title: "Ready for a website that matches the [[quality]] of your work?",
      body: "If your current site no longer reflects how professional your business really is, let's look together at what a modern premium presence could look like for you.",
      primary: "Book a free initial consultation",
      secondary: "View examples",
      micro: "Reply within 24 h · no consultation fee · in German or English",
    },
    footer: {
      tag: "Premium websites for local service businesses across Germany. Strategy, design and build from a single team.",
      colA: "Services", colALinks: [["Website project", "#leistungen"], ["Sub-pages", "#leistungen"], ["Ongoing care", "#leistungen"], ["Process", "#ablauf"]],
      colB: "Company", colBLinks: [["About Heller", "#"], ["References", "#referenzen"], ["FAQ", "#faq"], ["Contact", "#kontakt"]],
      colC: "Contact", colCLinks: [["hallo@heller.de", "mailto:hallo@heller.de"], ["+49 30 000 000", "tel:+4930000000"], ["LinkedIn", "#"]],
      copyright: "© 2026 Heller. All rights reserved.",
      legal: [["Imprint", "#"], ["Privacy", "#"], ["Terms", "#"]],
    },
  },
} as const;

export const HELLER_DICT: Record<string, any> = DICT_BASE;
export type Lang = 'de' | 'en';
